import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/layouts/navbar";
import { ThemeProvider } from "@/context/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <div className="min-h-screen flex flex-col space-y-4">
        <Navbar />
        <div className="flex-1">{children}</div>
      </div>
    </ThemeProvider>
  );
}
